### ISSUE TITLE
Playground for each example

### ISSUE THREAD

**Issue by proyb6** [disksing/iter#3]
For devs coming from other languages, do you plan to create a playground or web contents to demonstrate how each algorithm or API works? Benchmark between imperative and iter's approach could be nice to get the idea if there are impact to the performance and memory usage?

**Comment by disksing** [comment]
Thanks. Although I haven't considered this before, I think it's a good idea. However, this should not be done in the near future. My next step is to foucs on improving the wiki documentation.

**Comment by proyb6** [comment]
Noted, this could be close.
