### ISSUE TITLE
Add Golang-CI?

### ISSUE THREAD

**Issue by proyb6** [disksing/iter#4]
Golang-CI has a comprehensive check over GoReportCard, it's free for public repo.
https://golangci.com/

**Comment by disksing** [comment]
It is already connected to golangci. I just didn't find a way to add its badge.

**Comment by proyb6** [comment]
I read they are planned and have suggested to use their static badge temporary.
https://github.com/golangci/golangci-web/blob/master/src/assets/images/badge_a_plus_flat.svg

**Comment by disksing** [comment]
oh, good to know. But I think it's better not to use it due to potential risk that we are downgraded by future commits while the static badge can not be updated. We can leave the issue open util there is better solution.
